In [3]:
import os
import requests
import pandas as pd
import altair as alt
from io import StringIO
from datetime import datetime
from datetime import date
import math
from pandas.api.types import CategoricalDtype
import requests
from zipfile import ZipFile

Q = Globale straling (in J/cm2) per uurvak / Global radiation (in J/cm2) during the hourly division
SQ = Duur van de zonneschijn (in 0.1 uren) per uurvak, berekend uit globale straling (-1 for <0.05 uur) / Sunshine duration (in 0.1 hour) during the hourly division, calculated from global radiation (-1 for <0.05 hour)
DR = Duur van de neerslag (in 0.1 uur) per uurvak / Precipitation duration (in 0.1 hour) during the hourly division
RH = Uursom van de neerslag (in 0.1 mm) (-1 voor <0.05 mm) / Hourly precipitation amount (in 0.1 mm) (-1 for <0.05 mm)

In [4]:
def RetrieveStation_r2_uurdata(station,period):
    
#     url = "https://cdn.knmi.nl/knmi/map/page/klimatologie/gegevens/daggegevens/etmgeg_278.zip"
    url1 = "https://cdn.knmi.nl/knmi/map/page/klimatologie/gegevens/uurgegevens/"
    url2 = "uurgeg_"
    url3 = ''.join([str(station),period])
    url4 = ".zip"
    url = [url1,url2,url3,url4]
    url = ''.join(url)
    
    chunk_size=128
    save_path = ''.join([url2,url3,url4])
    r = requests.get(url, stream=True)
    with open(save_path, 'wb') as fd:
        for chunk in r.iter_content(chunk_size=chunk_size):
            fd.write(chunk)
    
    with ZipFile(save_path) as z:
        fn_text = ''.join([url2,url3,".txt"])
        with z.open(fn_text) as f:
            df = pd.read_csv(f, header=1, delimiter=",",skiprows=29)
    
    df['YYYYMMDD'] = pd.to_datetime(df['YYYYMMDD'],format='%Y%m%d')
#     # remove leading white spaces in column names
    df.columns = df.columns.str.replace(' ','')
    df['tijd'] = pd.to_datetime(df['YYYYMMDD'].astype(str) +' '+ (df['HH']-1).astype(str) +':00:00')
    df['month_nr'] = df['tijd'].dt.month
    df['yr'] = df['tijd'].dt.year
    
    df.rename(columns={"YYYYMMDD": "dag"},inplace=True)
    df.set_index('tijd',inplace = True)
    cols = df.columns
    
#     df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
    
    return df
#     return save_path

In [5]:
def RetrieveStation_r1_uurdata(station):
    
#     url = "https://cdn.knmi.nl/knmi/map/page/klimatologie/gegevens/daggegevens/etmgeg_278.zip"
    url1 = "https://cdn.knmi.nl/knmi/map/page/klimatologie/gegevens/uurgegevens/"
    url2 = "uurgeg_"
    url3 = ''.join([str(station),'_2021-2030'])
    url4 = ".zip"
    url = [url1,url2,url3,url4]
    url = ''.join(url)
    
    chunk_size=128
    save_path = ''.join([url2,url3,url4])
    r = requests.get(url, stream=True)
    with open(save_path, 'wb') as fd:
        for chunk in r.iter_content(chunk_size=chunk_size):
            fd.write(chunk)
    
    with ZipFile(save_path) as z:
        fn_text = ''.join([url2,url3,".txt"])
        with z.open(fn_text) as f:
            df = pd.read_csv(f, header=1, delimiter=",",skiprows=29)
    
    df['YYYYMMDD'] = pd.to_datetime(df['YYYYMMDD'],format='%Y%m%d')
#     # remove leading white spaces in column names
    df.columns = df.columns.str.replace(' ','')
    df['tijd'] = pd.to_datetime(df['YYYYMMDD'].astype(str) +' '+ (df['HH']-1).astype(str) +':00:00')
    
    df.rename(columns={"YYYYMMDD": "dag"},inplace=True)
    df.set_index('tijd',inplace = True)
    cols = df.columns
    
#     df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
    
    return df
#     return save_path

In [6]:
def GetKNMI_uurdata_r1(params_in):
    params = params_in.split(",")
    
    df1 = RetrieveStation_r2_uurdata(278,'_2011-2020') #278 is Heino
    df2 = RetrieveStation_r2_uurdata(278,'_2021-2030') #278 is Heino
    df = pd.concat([df1,df2])
    #response, disclaimer, legend, header, df = RetrieveStation('260') #260 is De Bilt
    
    return df[params]

In [7]:
param_gn = 'HH,SQ,Q,DR,T,FH,RH,dag,month_nr,yr'
df = GetKNMI_uurdata_r1(param_gn)

In [9]:
df.tail(30)

                     HH  SQ   Q  DR   T  FH  RH        dag  month_nr    yr
tijd
2022-11-27 18:00:00  19   0   0  10  68  30   3 2022-11-27        11  2022
2022-11-27 19:00:00  20   0   0  10  65  30   7 2022-11-27        11  2022
2022-11-27 20:00:00  21   0   0  10  63  30  11 2022-11-27        11  2022
2022-11-27 21:00:00  22   0   0  10  63  30  11 2022-11-27        11  2022
2022-11-27 22:00:00  23   0   0   8  63  30  11 2022-11-27        11  2022
2022-11-27 23:00:00  24   0   0   0  66  30  -1 2022-11-27        11  2022
2022-11-28 00:00:00   1   0   0   0  68  30   0 2022-11-28        11  2022
2022-11-28 01:00:00   2   0   0   0  72  30   0 2022-11-28        11  2022
2022-11-28 02:00:00   3   0   0   0  75  30   0 2022-11-28        11  2022
2022-11-28 03:00:00   4   0   0   0  73  30  -1 2022-11-28        11  2022
2022-11-28 04:00:00   5   0   0   0  75  30   0 2022-11-28        11  2022
2022-11-28 05:00:00   6   0   0   0  75  30   0 2022-11-28        11  2022
2022-11-28 06:00:00   7   0   0   4  75  40   3 2022-11-28        11  2022
2022-11-28 07:00:00   8   0   1   8  76  30   2 2022-11-28        11  2022
2022-11-28 08:00:00   9   0   5  10  77  30   8 2022-11-28        11  2022
2022-11-28 09:00:00  10   0  14  10  80  30   5 2022-11-28        11  2022
2022-11-28 10:00:00  11   0  23  10  83  20   3 2022-11-28        11  2022
2022-11-28 11:00:00  12   0  23   0  84  20  -1 2022-11-28        11  2022
2022-11-28 12:00:00  13   0  16   0  84  20  -1 2022-11-28        11  2022
2022-11-28 13:00:00  14   0  10   0  85  20   0 2022-11-28        11  2022
2022-11-28 14:00:00  15   0   6   0  86  10   0 2022-11-28        11  2022
2022-11-28 15:00:00  16   0   1   0  87  20   0 2022-11-28        11  2022
2022-11-28 16:00:00  17   0   0   0  85  10   0 2022-11-28        11  2022
2022-11-28 17:00:00  18   0   0   0  85  10   0 2022-11-28        11  2022
2022-11-28 18:00:00  19   0   0   0  86  10   0 2022-11-28        11  2022
2022-11-28 19:00:00  20   0   0   0  86  10   0 2022-11-28        11  2022
2022-11-28 20:00:00  21   0   0   0  84  10   0 2022-11-28        11  2022
2022-11-28 21:00:00  22   0   0   0  86  10   0 2022-11-28        11  2022
2022-11-28 22:00:00  23   0   0   0  84  10   0 2022-11-28        11  2022
2022-11-28 23:00:00  24   0   0   0  79  20   0 2022-11-28        11  2022

In [4]:
B=20000
r=0.04
n=20

In [5]:
B*r / (1-(1+r)**(-n))

1471.635006572577